version: '3'
services:
  faceapi:
    restart: always
    build: .
#    command: flask run -h 0.0.0.0 -p 5000
    container_name: 'faceapi'
    working_dir: '/root/face-api/'
    tty: true
    volumes:
      - ./face-api:/root/face-api
      - ./:/usr/src/app
    ports:
#      - "5000:5000"
      - "3030:3000"
    stdin_open: true